// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Tue Sep  2 00:24:11 2025

top_lcd top_lcd_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.IRDA_RXD(IRDA_RXD_sig) ,	// input  IRDA_RXD_sig
	.lcd_button(lcd_button_sig) ,	// input  lcd_button_sig
	.lcd_rs(lcd_rs_sig) ,	// output  lcd_rs_sig
	.lcd_en(lcd_en_sig) ,	// output  lcd_en_sig
	.lcd_rw(lcd_rw_sig) ,	// output  lcd_rw_sig
	.lcd_out_on(lcd_out_on_sig) ,	// output  lcd_out_on_sig
	.lcd_data(lcd_data_sig) 	// output [7:0] lcd_data_sig
);

