// megafunction wizard: %FIFO%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: dcfifo 

// ============================================================
// File Name: fifo_async.v
// Megafunction Name(s):
//          dcfifo
//
// Simulation Library Files(s):
//          altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 24.1std.0 Build 1077 03/04/2025 SC Lite Edition
// ************************************************************

//Copyright (C) 2025  Altera Corporation. All rights reserved.
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and any partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, the Altera Quartus Prime License Agreement,
//the Altera IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Altera and sold by Altera or its authorized distributors.  Please
//refer to the Altera Software License Subscription Agreements 
//on the Quartus Prime software download page.

// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module fifo_async (
    aclr,
    data,
    rdclk,
    rdreq,
    wrclk,
    wrreq,
    q,
    rdempty,
    wrfull);

    input   aclr;
    input   [11:0]  data;
    input   rdclk;
    input   rdreq;
    input   wrclk;
    input   wrreq;
    output   [11:0]  q;
    output   rdempty;
    output   wrfull;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
    tri0   aclr;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

    wire [11:0] sub_wire0;
    wire  sub_wire1;
    wire  sub_wire2;
    wire [11:0] q = sub_wire0[11:0];
    wire  rdempty = sub_wire1;
    wire  wrfull = sub_wire2;

    dcfifo   dcfifo_component (
                .aclr (aclr),
                .data (data),
                .rdclk (rdclk),
                .rdreq (rdreq),
                .wrclk (wrclk),
                .wrreq (wrreq),
                .q (sub_wire0),
                .rdempty (sub_wire1),
                .wrfull (sub_wire2),
                .eccstatus (),
                .rdfull (),
                .rdusedw (),
                .wrempty (),
                .wrusedw ());
    defparam
        dcfifo_component.intended_device_family = "Cyclone IV E",
        dcfifo_component.lpm_numwords = 1024,
        dcfifo_component.lpm_showahead = "OFF",
        dcfifo_component.lpm_type = "dcfifo",
        dcfifo_component.lpm_width = 12,
        dcfifo_component.lpm_widthu = 10,
        dcfifo_component.overflow_checking = "ON",
        dcfifo_component.rdsync_delaypipe = 5,
        dcfifo_component.read_aclr_synch = "OFF",
        dcfifo_component.underflow_checking = "ON",
        dcfifo_component.use_eab = "ON",
        dcfifo_component.write_aclr_synch = "OFF",
        dcfifo_component.wrsync_delaypipe = 5;

endmodule